# -*- coding: utf-8 -*-
"""lr cl ml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Row_R-gSYUxa2vEn-ilZrrQeVufNMArl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ML PY/diabetes.csv

df = pd.read_csv('diabetes.csv')

df.head()

df.shape

df.info()

df.isnull().sum()



from sklearn.model_selection import train_test_split

x=df.iloc[:,df.columns!='Outcome']
y=df.iloc[:,df.columns=='Outcome']

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier()

model.fit(xtrain,ytrain.values.ravel())

a=model.predict(xtest)



print(a)

from sklearn.metrics import accuracy_score

acc=accuracy_score(a,ytest)

print(acc)

